### PR TITLE
Loosen restrictions on hostname TLDs regarding numeric digits

### LINKED ISSUE #18: Invalid host name error when it starts with a number
Hey folks, we're seeing an interesting error when we migrated to Hapi 20. When we start a Hapi server on a docker host for example, using 

```
this.server = Hapi.server({
    port: this.options.port,
    host: this.options.host 
});
```

In this case the hostname is an autogenerated alphanumeric. If the hostname starts with a number, we see an error:

`"host" must be a valid hostname`

Here's my analysis, when the host is just the hostname without any domain and tld suffix, the number of segments [here](https://github.com/hapijs/validate/blob/5882293234866528de6406a823098b8f9ed9499b/lib/types/string.js#L691) is `1`.

And in the loop, [it gets tested if it is a tdlSegment](https://github.com/hapijs/validate/blob/5882293234866528de6406a823098b8f9ed9499b/lib/types/string.js#L710). Since the hostname starts with a number, it fails here. 

I believe if the number of segments is 1, we can assume that it is the hostname(machine name) and not a tdlSegment. In which case, we test it for a domainSegment.

Please let me know your thoughts.

### PR DESCRIPTION
**Pull request by devinivy**
Fixes #18.  From our conversation there:
> There are protections related to the TLD's validation primarily in order to make it possible to distinguish an IP versus a domain. I believe a sound interpretation is to relax the TLD validation from requiring it to start with an alphabetic character to ensuring that it is not _all-numeric_. This is supported by [RFC 3696 section 2](https://tools.ietf.org/html/rfc3696#section-2)'s clarification to RFC 1123. See also https://serverfault.com/a/638270. I believe docker [is careful](https://github.com/docker/docker-ce/blob/6c81bbd59d78f35499d47a5832656b727e9925a0/components/engine/pkg/stringid/stringid.go#L47-L49) not to create all-numeric hostnames.

Previously TLDs were validated by requiring that the first character not be a numeric digit.  This PR relaxes that requirement to just ensure it contains _any_ character which is not a numeric digit, which seems to me like a more up-to-date interpretation of specs and will give Docker users less trouble.  It is also more in-line with versions of joi prior to v17.

### CODE REVIEW

File: lib/types/string.js [hunk 1]
```diff
@@ -701,15 +701,19 @@ internals.isDomainValid = function (domain) {
             return false;
         }
 
-        if (i < segments.length - 1) {
-            if (!internals.domainSegmentRx.test(segment)) {
-                return false;
-            }
+        // Here's we're following RFC 1035 and 1123, plus 3696's clarification
```
Comment (devinivy) [inline lib/types/string.js]:
```suggestion
        // Here we're following RFC 1035 and 1123, plus 3696's clarification
```

**Comment by kanongil** [comment]
Hostnames should never be validated as a tld, so this should be able to be simplified further (and renamed to `isHostnameValid()`.

Incidentally, hostnames should not be punycode resolved, but it works out for Hapi, since the host validation also needs to support domain names (which need the resolve).

I guess the `hostname()` check is best renamed to `host()` to better signal that it matches more than hostnames.

As far as I can tell, the `hostname()` validation is only used in hapi itself. The only other use is in [bell](https://github.com/hapijs/bell/blob/b6569e8d6a3782a82ed8d1fc004cda0375fbe884/lib/providers/auth0.js#L8), but it uses the Joi version and should probably be using `domain()`.

**Comment by kanongil** [comment]
Also, a test that fails on an all-numeric hostname would be appropriate.

**Comment by devinivy** [comment]
> Hostnames should never be validated as a tld, so this should be able to be simplified further (and renamed to `isHostnameValid()` ... I guess the `hostname()` check is best renamed to `host()` to better signal that it matches more than hostnames.

I think this is a little bit open-ended.  A hostname could be defined as just the local name `my-host` or it could be the FQDN `my-host.hapi.dev` depending on who you ask and what software you're using.  I believe here it is intended to be the same sense as, for example, `HostName` in an SSH config: anything that can be resolved to an IP address.  Whether the last segment is an actual TLD may or may not be the case (it isn't for `my-host`, but it is for `my-host.hapi.dev`), but as I understand it the same rule applies specifically to make it simple to distinguish an IP from a local hostname or domain name: the last segment—even if there's only one—can't be all-numeric.

If you think this seems off, of course I am open to making changes.  I think that the terminology isn't perfectly rigid or well-defined, unfortunately, and that the current sense of the term "hostname" here to mean "anything that can resolve to an IP" is fine by at least some standards and is the original intention here.  Most importantly: let me know if you think that the current behavior is wrong— I couldn't tell if you thought that was the case or not.  I am hoping to make just an incremental bugfix here, but we could plan and make further changes to this area of validation in the future too.

> Also, a test that fails on an all-numeric hostname would be appropriate.

Luckily there was already a test for this, so I didn't need to add one 👍

**Comment by kanongil** [comment]
It is not possible to determine, from a hostname string, whether any trailing part of it is actually a TLD part, when the hostname does not have a trailing `.`. This is because a hostname must otherwise be resolved against the domain search path to turn it into a FQDN. This also applies to the string `my-host.hapi.dev`, which could actually mean `my-host.hapi.dev.whatever.com`. There is no way to know from the string itself.

As you correctly point out, hapi essentially just wants a string that can be resolved to an ip address. Be it through a hostname, a proper domain name, or an ip string. As such, this implementation seems to work. Except:

1. Doing a test against a TLD part seems wrong, since it might not actually be a TLD part.
1. There is another bug: A hostname with a trailing `.`, eg. `myhost.example.` does not pass the test.

Given that the checked host will likely end up in a socket `.listen()` call, erroring at that point, the check can be made more lenient without any real harm. As such, I would just drop the number-only check from your patch. This would also match a standard ip address: `1.2.3.4`, which will be fine, since the [next check](https://github.com/hapijs/validate/blob/5882293234866528de6406a823098b8f9ed9499b/lib/types/string.js#L342) would match it anyway.

**Comment by devinivy** [comment]
> Doing a test against a TLD part seems wrong, since it might not actually be a TLD part.

Wouldn't `my-host.hapi.123` be an invalid local hostname (even without a TLD) because the last part is all-numeric?  I believe it is the same rule that makes a fully-numeric hostname invalid (e.g. `12345`).  That is my interpretation of the specs (RFCs 1035 and 952 -> 1123 -> 3693) at least—I am interested if that seems off to you and others, as I hope to get this right!  As far as I can tell the specs apply the same principle to local hostnames and fully-qualified domain names equally.  In all cases the idea is to make it easy to distinguish an IP from any of these other things.  If we continue the direction I have already headed, I will certainly remove the historical reference to "TLD" in the code in order to clarify this.

> Given that the checked host will likely end up in a socket .listen() call, erroring at that point, the check can be made more lenient without any real harm.

I am personally in favor of fixing this localized issue where we're not quite validating to spec rather than allowing things through that are verifiably not allowed (for example, what about a hostname which isn't an IP but has all numeric parts? `999.999.999.0001`).  But if a second reviewer agrees with that idea, I will happily follow suit!  I think we really could use a third person to take a look, ha!

**Comment by devinivy** [comment]
> I couldn't find a section that specifies that fully-numeric hostnames are invalid (perhaps I missed it).

I think I can motivate this based on the spec!  As you cited above from 1123:
> at least the highest-level component label will be alphabetic

The ambiguity is in the word "alphabetic": should the highest-level label (or in the hapi code, "last segment") be all-alphabetic (this would be very strict), or simply not all-numeric?  I think it's pretty clear that it should mean "not all-numeric", but RFC 3696 clarifies this in summarizing the validation proposed by past RFCs that touch on hostnames:

> There is an additional rule that essentially requires that top-level domain names not be all-numeric.

I believe they are referencing 1123 here, and in turn sort of stretching the meaning of the term "TLD" how the hapi code does.   But I believe they are clarifying the rule around "the highest-level component label."  Also note that if there's only one segment then it is going to be the "highest-level component label."  To answer your question: in my opinion this is how the spec can be applied to see that an all-numeric hostname is invalid.

There is nothing in specs that I saw that supports the way hapi previously validated the last segment: it ensured it was not all-numeric by strictly requiring its first character be alphabetic.  This PR relaxes that to require that the last segment validates as any other segment but additionally has _some_ non-numeric character in it (not necessarily the first character).

**Comment by hueniverse** [comment]
It would be helpful to know if any conclusion here applies to joi.

**Review by smilebot — APPROVED** [review]

**Review by Nargonath — COMMENTED** [review]
I'm in favor of allowing the last segment to contain digits as long as it is not all-numeric characters rather than relying on socket `listen()` call to validate it for us. It's more explicit what we determine as valid in the former. Also the same validation rules apply on the last segment be it from a FQDN or an hostname AFAIU. I don't see what would be the problem if we were to validate the last segment with these new rules and it was part of a FQDN.

However as @kanongil pointed out, we do not handle the trailing dot case. Shouldn't we handle it too?

**Review by kanongil — APPROVED** [review]

File: lib/types/string.js [hunk 2]
```diff
@@ -42,7 +42,7 @@ const internals = {
 
     domainControlRx: /[\x00-\x20@\:\/]/,                                                // Control + space + separators
     domainSegmentRx: /^[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?$/,
-    tldSegmentAdditionalRx: /[^0-9]/                                                    // Domain segment which is additionally not all-numeric
+    finalSegmentAdditionalRx: /[^0-9]/                                                    // Domain segment which is additionally not all-numeric
```
Comment (devinivy) [inline lib/types/string.js]:
```suggestion
    finalSegmentAdditionalRx: /[^0-9]/                                                  // Domain segment which is additionally not all-numeric
```

**Comment by devinivy** [comment]
@hueniverse this does apply to joi, and a comparable fix will go [here](https://github.com/sideway/address/blob/36c1b3e2c11573ce0230135ca8845228e96fe94e/lib/domain.js#L83-L92) in address.  As part of this work we also logged #20 which applies to joi too.
